<?php
/**
 * @file
 * Alter Islandora forms : dependent/controlled metadata fields for UNB Scholar.
 */

define('UNBSCHOLAR_ISLANDORA_FORM_OPERATIONS_TYPE_FIELD', 'formDataType');

/**
 * Implements hook_form_alter().
 */
function unbscholar_islandora_form_operations_form_alter(&$form, &$form_state, $form_id) {
  if (($form_id == 'xml_form_builder_datastream_form' || $form_id == 'islandora_ingest_form') && isset($form[UNBSCHOLAR_ISLANDORA_FORM_OPERATIONS_TYPE_FIELD])) {

    define('UNBSCHOLAR_ISLANDORA_FORM_OPERATIONS_ROOT', DRUPAL_ROOT . '/' . drupal_get_path('module', 'unbscholar_islandora_form_operations'));
    define('UNBSCHOLAR_ISLANDORA_FORM_OPERATIONS_DATA_PATH', UNBSCHOLAR_ISLANDORA_FORM_OPERATIONS_ROOT . '/data');

    $form_alter_operations_include_file = UNBSCHOLAR_ISLANDORA_FORM_OPERATIONS_ROOT . "/includes/{$form[UNBSCHOLAR_ISLANDORA_FORM_OPERATIONS_TYPE_FIELD]['#value']}.inc";
    if (file_exists($form_alter_operations_include_file)) {
      include_once "$form_alter_operations_include_file";
      $form_alter_operations_function = "_unbscholar_islandora_form_operations_{$form[UNBSCHOLAR_ISLANDORA_FORM_OPERATIONS_TYPE_FIELD]['#value']}_form_alter";
      if (function_exists($form_alter_operations_function)) {
        include_once UNBSCHOLAR_ISLANDORA_FORM_OPERATIONS_ROOT . '/includes/common.inc';
        $form_alter_operations_function($form, $form_state);
      }
    }

  }
}

/**
 * Implements hook_CMODEL_islandora_view_object().
 */
function unbscholar_islandora_form_operations_ir_thesisCModel_islandora_view_object(AbstractObject $object) {
  if (_unbscholar_islandora_form_operations_datastream_exists_user_unauth($object, 'PDF')) {
    drupal_set_message(
      t(
        'Additional resources related to this item are available, however they are restricted to the UNB community. To view them, please <a href="@login_url">Login</a>.',
        array(
          '@login_url' => '/user/login?destination=' . current_path(),
        )
      ),
      'warning'
    );
  }
}

/**
 * Determine if a tuque AbstractObject has a datastream the user cannot access.
 *
 * @param AbstractObject $object
 *   The tuque AbstractObject object to view.
 * @param string $datastream_label
 *   The datastream label to check.
 *
 * @return bool
 *   Returns TRUE if the AbstractObject has a datastream with $datastream_label
 *   that the current user cannot access. FALSE otherwise.
 */
function _unbscholar_islandora_form_operations_datastream_exists_user_unauth(AbstractObject $object, $datastream_label) {
  $pdf_datastream_exists = isset($object[$datastream_label]);
  $user_datastream_access = islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $object[$datastream_label]);
  if ($pdf_datastream_exists && $user_datastream_access == FALSE) {
    return TRUE;
  }
  return FALSE;
}
